name: "Feature request"
description: "You have a neat idea that should be implemented?"
labels: ["enhancement", "0. to triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### 👍 Thanks for reporting issues back to Nextcloud!
        This is the issue tracker of Nextcloud, if you have any support question please check out [support](https://nextcloud.com/support)
        To make it possible for us to help you please fill out below information carefully.
        
        If you have any questions, head over to the [forums](https://help.nextcloud.com/c/apps/calendar).
        Note that Nextcloud is an open source project backed by Nextcloud GmbH. Most of our volunteers are home users and thus primarily care about issues that affect home users. Our paid engineers prioritize issues of our customers. If you are neither a home user nor a customer, consider paying somebody to implement the feature or enhancement you'd like, do it yourself or [become a customer](https://nextcloud.com/enterprise/).
  - type: textarea
    id: description-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: description-solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
  - type: textarea
    id: description-alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
