// SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

export type TalkRoom = {
	actorId: string
	invitedActorId: string
	actorType: string
	attendeeId: number
	attendeePermissions: number
	attendeePin: string
	avatarVersion: string
	breakoutRoomMode: number
	breakoutRoomStatus: number
	callFlag: number
	callPermissions: number
	callRecording: number
	callStartTime: number
	canDeleteConversation: boolean
	canEnableSIP: boolean
	canLeaveConversation: boolean
	canStartCall: boolean
	defaultPermissions: number
	description: string
	displayName: string
	hasCall: boolean
	hasPassword: boolean
	id: number
	isCustomAvatar: boolean
	isFavorite: boolean
	lastActivity: number
	lastCommonReadMessage: number
	lastMessage: string
	lastPing: number
	lastReadMessage: number
	listable: number
	liveTranscriptionLanguageId: string
	lobbyState: number
	lobbyTimer: number
	mentionPermissions: number
	messageExpiration: number
	name: string
	notificationCalls: number
	notificationLevel: number
	objectId: string
	objectType: string
	participantFlags: number
	participantType: number
	permissions: number
	readOnly: number
	recordingConsent: number
	remoteServer: string
	remoteToken: string
	sessionId: string
	sipEnabled: number
	status: string
	statusClearAt: number
	statusIcon: string
	statusMessage: string
	token: string
	type: number
	unreadMention: boolean
	unreadMentionDirect: boolean
	unreadMessages: number
	isArchived: boolean
	isImportant: boolean
	isSensitive: boolean
	invalidParticipants?: {
		users?: string[]
		federated_users?: string[]
		groups?: string[]
		emails?: string[]
		phones?: string[]
		teams?: string[]
	}
}
