name: PHP AppCode Check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
        nextcloud-versions: ['master']
    name: AppCode check
    steps:
      - name: Set up php${{ matrix.php-versions }}
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip
          coverage: xdebug
      - name: Checkout Nextcloud
        run: git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b ${{ matrix.nextcloud-versions }} nextcloud
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: nextcloud/apps/calendar
      - name: App Code check
        working-directory: nextcloud
        run: php occ app:check-code calendar
