# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Block merges for EOL branches

on:
  pull_request:
    branches:
      - main
      - stable6.5

permissions:
  contents: read

concurrency:
  group: block-merge-eol-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  block-merges-eol:
    name: Block merges for EOL branches
    runs-on: ubuntu-latest-low

    steps:
      - name: Confirm base branch is allowed
        env:
          BASE_REF: ${{ github.base_ref }}
        run: echo "Pull requests targeting $BASE_REF are allowed."
